<?php
require_once __DIR__ . '/community/inc/auth.php';
$u = current_user();

$posts = db()->query(
    "SELECT p.id, p.type, p.channel, p.title, p.slug, p.excerpt, p.body, p.approved_at, u.username,
            (SELECT GROUP_CONCAT(DISTINCT kind ORDER BY kind SEPARATOR ',') FROM media m WHERE m.post_id = p.id) AS kinds,
            (SELECT COUNT(*) FROM posts p2 WHERE p2.channel = p.channel AND p2.type = p.type AND p2.status = 'approved'
               AND (p2.approved_at < p.approved_at OR (p2.approved_at = p.approved_at AND p2.id <= p.id))) AS seq
     FROM posts p JOIN users u ON u.id = p.user_id
     WHERE p.status = 'approved' AND p.channel = 'site' AND p.type = 'transmission'
     ORDER BY p.approved_at DESC LIMIT 100"
)->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Feed — TRANSMISSION</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>

<header class="site-head">
  <div class="brand">
    TRANSMISSION
  </div>
  <nav>
    <a href="./" class="current">Feed</a>
    <a href="notes.php">Notes</a>
    <a href="directory.php">Index</a>
    <a href="community/">Community</a>
<?php if ($u): ?>
    <a href="community/write.php">Write</a>
    <a href="community/edit.php">Edit</a>
<?php if ($u['is_admin']): ?>
    <a href="community/moderate.php">Moderate</a>
<?php endif; ?>
    <a href="community/logout.php">Log out · <?= e($u['username']) ?></a>
<?php else: ?>
    <a href="community/login.php">Log in</a>
    <a href="community/register.php">Join</a>
<?php endif; ?>
  </nav>
</header>

<div class="meta-bar">
  <span>Voice-originated transmissions &amp; framework notes</span>
</div>

<main>

<?php if (!$posts): ?>
  <div class="empty-state">Nothing published yet.</div>
<?php endif; ?>
<?php foreach ($posts as $p): ?>
  <article class="entry">
    <div class="stamp">
      <div class="date"><?= e(date('d/m/Y', strtotime($p['approved_at']))) ?></div>
      <div class="no type-line"><?= e(strtoupper($p['type'])) ?> <?= e(str_pad((string) $p['seq'], 4, '0', STR_PAD_LEFT)) ?></div>
    </div>
    <div class="body">
      <div class="serif-title"><?= e($p['title']) ?></div>
      <div class="serif-excerpt">
        <?= e($p['excerpt'] !== '' ? $p['excerpt'] : mb_substr(preg_replace('/\s+/', ' ', $p['body']), 0, 140) . '…') ?>
      </div>
      <div class="micro">
<?php if (!empty($p['kinds'])): ?>
<?php foreach (explode(',', $p['kinds']) as $k): ?>
        <span><?= e(strtoupper($k)) ?></span>
<?php endforeach; ?>
<?php endif; ?>
      </div>
      <a class="more" href="<?= e(post_url($p)) ?>">Open <?= e($p['type']) ?> →</a>
    </div>
  </article>
<?php endforeach; ?>

</main>

<aside class="attribution">
  <span class="label">Authorship note</span>
  All transmissions and notes on this site have been received and given by the author. They have <b>not</b> been generated by artificial intelligence. Claude has been used only for building the website that hosts them, and for transcribing into text the transmissions originally recorded in audio. Community posts are written and signed by their own authors, and reviewed before publication.
</aside>

<footer>
  <span>www.sciencecoherence.com</span>
</footer>

</body>
</html>
