<?php
require_once __DIR__ . '/community/inc/auth.php';
$u = current_user();

$rows = db()->query(
    "SELECT p.id, p.type, p.channel, p.title, p.slug, p.approved_at, u.username,
            (SELECT COUNT(*) FROM posts p2 WHERE p2.channel = p.channel AND p2.type = p.type AND p2.status = 'approved'
               AND (p2.approved_at < p.approved_at OR (p2.approved_at = p.approved_at AND p2.id <= p.id))) AS seq
     FROM posts p JOIN users u ON u.id = p.user_id
     WHERE p.status = 'approved'
     ORDER BY p.approved_at DESC"
)->fetchAll();

$transmissions = array_filter($rows, fn($r) => $r['channel'] === 'site' && $r['type'] === 'transmission');
$notes = array_filter($rows, fn($r) => $r['channel'] === 'site' && $r['type'] !== 'transmission');
$community = array_filter($rows, fn($r) => $r['channel'] !== 'site');

function index_table(array $rows, bool $showAuthor): void {
    if (!$rows) {
        echo '  <div class="empty-state">Nothing here yet.</div>' . "\n";
        return;
    }
    ?>
  <table class="log">
    <thead>
      <tr>
        <th style="width:120px;">DATE</th>
        <th style="width:80px;">No.</th>
        <th>TITLE</th>
        <th style="width:140px;"><?= $showAuthor ? 'AUTHOR' : 'TYPE' ?></th>
        <th style="width:100px;">STATUS</th>
      </tr>
    </thead>
    <tbody>
<?php foreach ($rows as $r): ?>
      <tr>
        <td><?= e(date('d/m/Y', strtotime($r['approved_at']))) ?></td>
        <td><?= e(str_pad((string) $r['seq'], 4, '0', STR_PAD_LEFT)) ?></td>
        <td><a href="<?= e(post_url($r)) ?>"><?= e($r['title']) ?></a></td>
        <td><?= $showAuthor ? e($r['username']) : e(strtoupper($r['type'])) ?></td>
        <td class="flag-ok">PUBLIC</td>
      </tr>
<?php endforeach; ?>
    </tbody>
  </table>
    <?php
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Index — TRANSMISSION</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>

<header class="site-head">
  <div class="brand">
    INDEX
  </div>
  <nav>
    <a href="./">Feed</a>
    <a href="notes.php">Notes</a>
    <a href="directory.php" class="current">Index</a>
    <a href="community/">Community</a>
<?php if ($u): ?>
    <a href="community/write.php">Write</a>
    <a href="community/edit.php">Edit</a>
<?php if ($u['is_admin']): ?>
    <a href="community/moderate.php">Moderate</a>
<?php endif; ?>
    <a href="community/logout.php">Log out · <?= e($u['username']) ?></a>
<?php else: ?>
    <a href="community/login.php">Log in</a>
    <a href="community/register.php">Join</a>
<?php endif; ?>
  </nav>
</header>

<div class="meta-bar">
  <span>Chronological index of all transmissions, notes &amp; community posts</span>
</div>

<main>
  <h2>Transmissions <span class="tag">Voice-originated</span></h2>
<?php index_table(array_values($transmissions), false); ?>

  <h2>Notes <span class="tag">Framework notes &amp; papers</span></h2>
<?php index_table(array_values($notes), false); ?>

  <h2>Community <span class="tag">Reader-contributed, reviewed</span></h2>
<?php index_table(array_values($community), true); ?>
</main>

<aside class="attribution">
  <span class="label">Authorship note</span>
  All transmissions and notes on this site have been received and given by the author. They have <b>not</b> been generated by artificial intelligence. Community posts are written and signed by their own authors, and reviewed before publication.
</aside>

<footer>
  <span>www.sciencecoherence.com</span>
</footer>

</body>
</html>
